### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by danielaciuperca** [danielsociu/PAO_project#1]
1. Any reason for leaving the default access for the fields in these classes? I would make them private.
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/models/Absence.java#L6
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/models/Grade.java#L6
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/models/Student.java#L6
2. You could use a Map implementation here, instead of List of Pair.
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/models/Class.java#L15
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/models/Teacher.java#L10
3. This can be done easier with a foreach.
https://github.com/danielsociu/PAO_project/blob/f5de835e934c0ee3cf656d29e9ae74b73cab630c/src/services/ClassService.java#L48

**Comment by danielsociu** [comment]
I solved them now, thanks :)
